
import { Translations, Review, FaqItem, BonusItem } from './types';

export const translations: Translations = {
    en: {
        bookNowNav: "Book Now",
        heroCTA: "GET MY SAVINGS NOW",
        heroSubtitle: "Book online to get an instant savings code. The more you spend, the more you save.",
        heroOffer: '<i data-lucide="sparkles" class="inline-block w-4 h-4 mr-1"></i> Exclusive Online Offer',
        detailsApply: "*Details Apply",
        ctaUrgency: "Exclusive Online Offer – Valid This Month Only",
        dragSlider: "Move the slider to see how much YOU could save.",
        repairCost: "Repair Cost", youSave: "You Save", finalCost: "Final Cost",
        oilChangeNote: "Oil changes count toward spend but are not discounted.",
        couponTitle: "What Repairs Can You Use This Coupon For?",
        couponSubtitle: "This discount applies to most of the repair work we do here at Queens Auto. That means you can save big on services like:",
        couponList1: `<li class="flex items-start"><i data-lucide="check-circle" class="w-5 h-5 text-cyan-400 mr-3 flex-shrink-0 mt-1"></i>Brake repairs & replacements</li>
                      <li class="flex items-start"><i data-lucide="check-circle" class="w-5 h-5 text-cyan-400 mr-3 flex-shrink-0 mt-1"></i>Suspension & steering work</li>
                      <li class="flex items-start"><i data-lucide="check-circle" class="w-5 h-5 text-cyan-400 mr-3 flex-shrink-0 mt-1"></i>Engine diagnostics & tune-ups</li>
                      <li class="flex items-start"><i data-lucide="check-circle" class="w-5 h-5 text-cyan-400 mr-3 flex-shrink-0 mt-1"></i>Batteries, alternators & starters</li>`,
        couponList2: `<li class="flex items-start"><i data-lucide="check-circle" class="w-5 h-5 text-cyan-400 mr-3 flex-shrink-0 mt-1"></i>Heating & A/C repairs</li>
                      <li class="flex items-start"><i data-lucide="check-circle" class="w-5 h-5 text-cyan-400 mr-3 flex-shrink-0 mt-1"></i>Belts, hoses & spark plugs</li>
                      <li class="flex items-start"><i data-lucide="check-circle" class="w-5 h-5 text-cyan-400 mr-3 flex-shrink-0 mt-1"></i>Electrical diagnostics</li>
                      <li class="flex items-start"><i data-lucide="check-circle" class="w-5 h-5 text-cyan-400 mr-3 flex-shrink-0 mt-1"></i>Fluid flushes & maintenance</li>`,
        couponExclusions: "<strong>Not included:</strong> Tires, oil changes, and state inspections.",
        bonusStackTitle: "Your Repair Comes With These FREE Bonuses",
        bonusStackSubtitle: "We pack in the value so you can drive away with total peace of mind.",
        bonus1Title: "Tiered Savings",
        bonus1Desc: "$50 OFF $500+ | $100 OFF $700+",
        bonus2Title: "Multi-Point Inspection",
        bonus2Desc: "A $79 Value, included for free.",
        bonus3Title: "Brake & Tire Safety Check",
        bonus3Desc: "A $39 Value, on us.",
        bonus4Title: "Roadside Assistance",
        bonus4Desc: "24/7 help, a $59 value.",
        bonus5Title: "Nationwide Warranty",
        bonus5Desc: "A powerful 2-Year / 24,000-Mile warranty.",
        bonusStackDisclaimer: "*Disclaimer: Warranty and roadside assistance are provided through ProVantage Auto Repair Network. See full terms for details.",
        step1Title: "Book", step1Desc: "Book online to get your savings code.",
        step2Title: "Show Up", step2Desc: "Bring your car. We’ll handle the rest.",
        step3Title: "Save", step3Desc: "Show your code to apply your discount.",
        formInstruction1: "Step 1 of 2 — Your contact and vehicle details.",
        formInstruction2: "Step 2 of 2 — When can you bring it in?",
        firstName: "First Name", lastName: "Last Name", email: "Email", mobileNumber: "Mobile Number",
        vehicleDetails: "Vehicle Details", carYear: "Year", carMake: "Make", carModel: "Model",
        nextButton: "Next &rarr; Pick a Time",
        whenBringIn: "When can you bring it in?",
        availableTimes: "Available Times",
        backButton: "&larr; Back",
        submitBtn: "Book My Service",
        testimonialsTitle: "Trusted by Elgin Drivers",
        testimonialsSubtitle: "Rated 4.9/5 Stars by 25,000+ customers who won’t go anywhere else.",
        loadMore: "Load More Reviews",
        readMore: "Read more",
        readLess: "Read less",
        aboutUs: "About Us",
        aboutTitle: "Driven by Passion for Cars — and Care for People.",
        aboutBody: "We’re not a big chain — we’re your neighborhood shop built on trust and a passion for what we do. Every car is treated like family, and every customer drives away knowing they got real value.",
        aboutTagline: "Real people. Real service. We fix the car — and the stress.",
        address: "<svg xmlns=\"http://www.w3.org/2000/svg\" width=\"16\" height=\"16\" viewBox=\"0 0 24 24\" fill=\"none\" stroke=\"currentColor\" stroke-width=\"2\" stroke-linecap=\"round\" stroke-linejoin=\"round\" class=\"inline-block lucide lucide-map-pin mr-2 h-4 w-4 text-cyan-400\"><path d=\"M20 10c0 6-8 12-8 12s-8-6-8-12a8 8 0 0 1 16 0Z\"></path><circle cx=\"12\" cy=\"10\" r=\"3\"></circle></svg>1303 Dundee Ave, 2 blocks from I-90, Elgin",
        serviceAreaTitle: "Proudly Serving Elgin & Beyond",
        serviceAreaSubtitle: "Your savings code is valid at our convenient Elgin location.",
        serviceAreaList: "Including Elgin, South Elgin, West Dundee, Sleepy Hollow, Gilberts, Streamwood, and Bartlett.",
        privacyPolicy: "Privacy Policy",
        termsOfUse: "Terms of Use",
        faqTitle: "Frequently Asked Questions",
        faqQ1: "How does the “Up to $100 Off” offer work?",
        faqA1: "It's a tiered system based on your spend. The more your repair costs, the more you save, up to a maximum of $100 off on spends of $700 or more.",
        faqQ2: "What if you have a better deal on brakes or wheel alignment?",
        faqA2: "You’ll always get the best deal we have. If a brake or alignment special saves you more than this coupon, we’ll give you that deal instead. Discounts don’t stack, but we make sure you always come out ahead.",
        faqQ3: "Can I combine this with other coupons or financing offers?",
        faqA3: "No, this offer can’t be combined with other promotions, coupons, or special financing. We always apply whichever discount saves you the most.",
        faqQ4: "Does this work for online and in-store appointments?",
        faqA4: "Yes. Claim your savings online here, then bring your vehicle in for service. Just mention your coupon when you check in at Queens Auto Service.",
        modalTitle: "Offer Details",
        modalP1: "Save up to $100. The discount is tiered based on total repair cost.",
        modalP2: "Excludes tires & state inspections. Oil changes count toward spend but are not discounted.",
        modalP3: "Cannot be combined with other offers. Valid only at Queens Auto Service in Elgin, IL.",
        popupTitleV2: "Wait! Don’t Miss This Auto Repair Package",
        popupSubtitleV2: "Get Your Tiered Discount + $150 in Free Bonuses When You Book Today.",
        popupBonus1: "Tiered Savings up to $100 OFF",
        popupBonus2: "Free Multi-Point Vehicle Inspection ($79 Value)",
        popupBonus3: "Free Brake & Tire Safety Check ($39 Value)",
        popupBonus4: "Roadside Assistance Included ($59 Value)",
        popupBonus5: "2-Year/24k Nationwide Warranty",
        popupCTAV2: "Claim My Repair Package →",
        bookingSuccess: "Booking...",

        // Thank You Page
        thankYouTitle: "Appointment Confirmed, {{name}}!",
        playMessageFor: "Play a message for {{name}}",
        yourCouponCodeIs: "Your coupon code is:",
        copied: "Copied!",
        confirmationText1: "Your spot is saved! We've sent a confirmation to your email and a text reminder to your phone.",
        confirmationText2: "Your {{vehicle}} is all set for its service.",
        playingAudio: "Playing...",
        playAgain: "Play message again",
        serviceTitle: "Service:",
        serviceValue: "Auto Repair Service",
        dateTimeTitle: "Date & Time:",
        locationTitle: "Location:",
        locationValue: "Queens Auto — Elgin",
        whatHappensNextTitle: "What Happens Next?",
        whatHappensNextStep1: "Check your text/email: We've sent a confirmation with your details.",
        whatHappensNextStep2: "We'll call to confirm: A team member will call you shortly to confirm everything.",
        whatHappensNextStep3: "Come on by: Head to the shop at your scheduled time. We'll be ready for you!",
        needToRescheduleTitle: "Need to Reschedule?",
        needToRescheduleBody: "No problem. Give us a call and we'll find a better time for you.",
        whereToFindUsTitle: "Where to Find Us",
        getDirections: "Get Directions",
        footerCopyright: "© {{year}} Queens Auto Service. All Rights Reserved.",

    },
    es: {
        bookNowNav: "Reservar Ahora",
        heroCTA: "OBTENER MIS AHORROS AHORA",
        heroSubtitle: "Reserva en línea para obtener un código de ahorro al instante. Cuanto más gastas, más ahorras.",
        heroOffer: '<i data-lucide="sparkles" class="inline-block w-4 h-4 mr-1"></i> Oferta Exclusiva en Línea',
        detailsApply: "*Aplican Detalles",
        ctaUrgency: "Oferta Exclusiva en Línea – Válida Solo Este Mes",
        dragSlider: "Mueve el control deslizante para ver cuánto podrías ahorrar.",
        repairCost: "Costo de Reparación", youSave: "Ahorras", finalCost: "Costo Final",
        oilChangeNote: "Los cambios de aceite cuentan para el gasto pero no tienen descuento.",
        couponTitle: "¿En Qué Reparaciones Puedes Usar Este Cupón?",
        couponSubtitle: "Este descuento se aplica a la mayoría de los trabajos de reparación que hacemos en Queens Auto. Eso significa que puedes ahorrar en grande en servicios como:",
        couponList1: `<li class="flex items-start"><i data-lucide="check-circle" class="w-5 h-5 text-cyan-400 mr-3 flex-shrink-0 mt-1"></i>Reparación y reemplazo de frenos</li>
                      <li class="flex items-start"><i data-lucide="check-circle" class="w-5 h-5 text-cyan-400 mr-3 flex-shrink-0 mt-1"></i>Trabajos de suspensión y dirección</li>
                      <li class="flex items-start"><i data-lucide="check-circle" class="w-5 h-5 text-cyan-400 mr-3 flex-shrink-0 mt-1"></i>Diagnóstico de motor y afinaciones</li>
                      <li class="flex items-start"><i data-lucide="check-circle" class="w-5 h-5 text-cyan-400 mr-3 flex-shrink-0 mt-1"></i>Baterías, alternadores y arranques</li>`,
        couponList2: `<li class="flex items-start"><i data-lucide="check-circle" class="w-5 h-5 text-cyan-400 mr-3 flex-shrink-0 mt-1"></i>Reparaciones de calefacción y A/C</li>
                      <li class="flex items-start"><i data-lucide="check-circle" class="w-5 h-5 text-cyan-400 mr-3 flex-shrink-0 mt-1"></i>Correas, mangueras y bujías</li>
                      <li class="flex items-start"><i data-lucide="check-circle" class="w-5 h-5 text-cyan-400 mr-3 flex-shrink-0 mt-1"></i>Diagnóstico eléctrico</li>
                      <li class="flex items-start"><i data-lucide="check-circle" class="w-5 h-5 text-cyan-400 mr-3 flex-shrink-0 mt-1"></i>Lavado de fluidos y mantenimiento</li>`,
        couponExclusions: "<strong>No incluido:</strong> Llantas, cambios de aceite e inspecciones estatales.",
        bonusStackTitle: "Tu Reparación Viene Con Estos Bonos GRATIS",
        bonusStackSubtitle: "Incluimos valor agregado para que puedas conducir con total tranquilidad.",
        bonus1Title: "Ahorros por Nivel",
        bonus1Desc: "$50 de DCTO en $500+ | $100 de DCTO en $700+",
        bonus2Title: "Inspección Multi-Punto",
        bonus2Desc: "Un valor de $79, incluido gratis.",
        bonus3Title: "Revisión de Seguridad de Frenos y Llantas",
        bonus3Desc: "Un valor de $39, por nuestra cuenta.",
        bonus4Title: "Asistencia en Carretera",
        bonus4Desc: "Ayuda 24/7, un valor de $59.",
        bonus5Title: "Garantía Nacional",
        bonus5Desc: "Una potente garantía de 2 años / 24,000 millas.",
        bonusStackDisclaimer: "*Aviso: La garantía y la asistencia en carretera son proporcionadas a través de ProVantage Auto Repair Network. Ver términos completos para más detalles.",
        step1Title: "Reserva", step1Desc: "Reserva en línea para obtener tu código de ahorro.",
        step2Title: "Visítanos", step2Desc: "Trae tu auto. Nosotros nos encargamos del resto.",
        step3Title: "Ahorra", step3Desc: "Muestra tu código para aplicar tu descuento.",
        formInstruction1: "Paso 1 de 2 — Tus datos de contacto y del vehículo.",
        formInstruction2: "Paso 2 de 2 — ¿Cuándo puedes traerlo?",
        firstName: "Nombre", lastName: "Apellido", email: "Correo Electrónico", mobileNumber: "Número de Celular",
        vehicleDetails: "Detalles del Vehículo", carYear: "Año", carMake: "Marca", carModel: "Modelo",
        nextButton: "Siguiente &rarr; Elige una Hora",
        whenBringIn: "¿Cuándo puedes traerlo?",
        availableTimes: "Horas Disponibles",
        backButton: "&larr; Atrás",
        submitBtn: "Reservar Mi Servicio",
        testimonialsTitle: "Con la Confianza de los Conductores de Elgin",
        testimonialsSubtitle: "Calificado 4.9/5 Estrellas por más de 25,000 clientes que no irán a ningún otro lado.",
        loadMore: "Cargar Más Reseñas",
        readMore: "Leer más",
        readLess: "Leer menos",
        aboutUs: "Sobre Nosotros",
        aboutTitle: "Impulsados por la Pasión por los Autos y el Cuidado por las Personas.",
        aboutBody: "No somos una gran cadena, somos tu taller de barrio construido sobre la confianza y la pasión por lo que hacemos. Cada auto es tratado como de la familia, y cada cliente se va sabiendo que obtuvo un valor real.",
        aboutTagline: "Gente real. Servicio real. Arreglamos el auto y el estrés.",
        address: "<svg xmlns=\"http://www.w3.org/2000/svg\" width=\"16\" height=\"16\" viewBox=\"0 0 24 24\" fill=\"none\" stroke=\"currentColor\" stroke-width=\"2\" stroke-linecap=\"round\" stroke-linejoin=\"round\" class=\"inline-block lucide lucide-map-pin mr-2 h-4 w-4 text-cyan-400\"><path d=\"M20 10c0 6-8 12-8 12s-8-6-8-12a8 8 0 0 1 16 0Z\"></path><circle cx=\"12\" cy=\"10\" r=\"3\"></circle></svg>1303 Dundee Ave, a 2 cuadras de la I-90, Elgin",
        serviceAreaTitle: "Sirviendo con Orgullo a Elgin y sus Alrededores",
        serviceAreaSubtitle: "Tu código de ahorro es válido en nuestra conveniente ubicación de Elgin.",
        serviceAreaList: "Incluyendo Elgin, South Elgin, West Dundee, Sleepy Hollow, Gilberts, Streamwood y Bartlett.",
        privacyPolicy: "Política de Privacidad",
        termsOfUse: "Términos de Uso",
        faqTitle: "Preguntas Frecuentes",
        faqQ1: "¿Cómo funciona la oferta de “Hasta $100 de Descuento”?",
        faqA1: "Es un sistema por niveles basado en tu gasto. Cuanto más cueste tu reparación, más ahorras, hasta un máximo de $100 de descuento en gastos de $700 o más.",
        faqQ2: "¿Qué pasa si tienen una mejor oferta en frenos o alineación de ruedas?",
        faqA2: "Siempre obtendrás la mejor oferta que tengamos. Si una oferta especial de frenos o alineación te ahorra más que este cupón, te daremos esa oferta. Los descuentos no se acumulan, pero nos aseguramos de que siempre salgas ganando.",
        faqQ3: "¿Puedo combinar esto con otros cupones u ofertas de financiamiento?",
        faqA3: "No, esta oferta no se puede combinar con otras promociones, cupones o financiamientos especiales. Siempre aplicamos el descuento que más te ahorre.",
        faqQ4: "¿Funciona para citas en línea y en la tienda?",
        faqA4: "Sí. Reclama tus ahorros en línea aquí y luego trae tu vehículo para el servicio. Solo menciona tu cupón al registrarte en Queens Auto Service.",
        modalTitle: "Detalles de la Oferta",
        modalP1: "Ahorra hasta $100. El descuento es por niveles según el costo total de la reparación.",
        modalP2: "Excluye llantas e inspecciones estatales. Los cambios de aceite cuentan para el gasto pero no tienen descuento.",
        modalP3: "No se puede combinar con otras ofertas. Válido solo en Queens Auto Service en Elgin, IL.",
        popupTitleV2: "¡Espera! No te pierdas este paquete de reparación",
        popupSubtitleV2: "Obtén tu Descuento por Nivel + $150 en Bonos Gratis al Reservar Hoy.",
        popupBonus1: "Ahorros por Nivel hasta $100 de DCTO",
        popupBonus2: "Inspección Vehicular Gratuita ($79 Valor)",
        popupBonus3: "Revisión de Seguridad de Frenos y Llantas Gratuita ($39 Valor)",
        popupBonus4: "Asistencia en Carretera Incluida ($59 Valor)",
        popupBonus5: "Garantía Nacional de 2 Años/24k Millas",
        popupCTAV2: "Reclamar Mi Paquete →",
        bookingSuccess: "Reservando...",

        // Thank You Page
        thankYouTitle: "¡Cita Confirmada, {{name}}!",
        playMessageFor: "Reproducir un mensaje para {{name}}",
        yourCouponCodeIs: "Tu código de cupón es:",
        copied: "¡Copiado!",
        confirmationText1: "¡Tu lugar está reservado! Hemos enviado una confirmación a tu correo y un recordatorio a tu teléfono.",
        confirmationText2: "Tu {{vehicle}} está listo para su servicio.",
        playingAudio: "Reproduciendo...",
        playAgain: "Reproducir de nuevo",
        serviceTitle: "Servicio:",
        serviceValue: "Servicio de Reparación de Auto",
        dateTimeTitle: "Fecha y Hora:",
        locationTitle: "Ubicación:",
        locationValue: "Queens Auto — Elgin",
        whatHappensNextTitle: "¿Qué Sigue Ahora?",
        whatHappensNextStep1: "Revisa tu texto/correo: Hemos enviado una confirmación con tus detalles.",
        whatHappensNextStep2: "Llamaremos para confirmar: Un miembro del equipo te llamará pronto para confirmar todo.",
        whatHappensNextStep3: "Visítanos: Dirígete al taller a la hora programada. ¡Estaremos listos para ti!",
        needToRescheduleTitle: "¿Necesitas Reprogramar?",
        needToRescheduleBody: "No hay problema. Llámanos y encontraremos un mejor momento para ti.",
        whereToFindUsTitle: "Dónde Encontrarnos",
        getDirections: "Obtener Direcciones",
        footerCopyright: "© {{year}} Queens Auto Service. Todos los Derechos Reservados.",
    }
};

export const testimonials: Review[] = [
    { "name": "Mark Devino", "text": "I got fast, friendly service here for a flat repair. Without any kind of appointment I got the tire fixed while I waited maybe 25 minutes. The repair was inexpensive. Great shop I will definitely be back." },
    { "name": "Bashar Danial", "text": "Gino and the Team, Wow!!! I recently had the misfortune of breaking down on the side of the road with a bad tire, called Queens Auto Service and spoke with Gino. They were very receptive and responsive, we got the vehicle to their shop, they immediately jumped into action and replaced the bad tire with a new tire and had us back on the road, all of this in under one hour!!! I highly recommend Queens Auto Service and Gino and the Team at this shop, top-notch!! Thank you for the help and great service." },
    { "name": "A C", "text": "HIGHLY RECOMMEND QUEENS TIRE IN ELGIN. Friendliness customer service. Prices are affordable, no extra unnecessary add ons. This will be my ONLY go to place. Much more than just tires" },
    { "name": "Nursultan Abeuov", "text": "Good place to get your tire, balancing, Alignment and more. Always good quality. Ill do all my pickup trucks alignment here, never regret it. Nick Abeuov🇰🇿" },
    { "name": "Kristin Kastern", "text": "Tires and axle shaft. They were amazing. I am new to the area and I am very happy 😊 with my service. They were honest and were able to fit me in on holiday weekend. The pricing was great. They even gave me really good advice about the car and tires. I am going to them in the future with all my cars. Thank you so much." },
    { "name": "Tim Chapman", "text": "Great customer service, went in for a second opinion for tire patch, nail in tire and advised not repairable too close to outer wall of tire. Good price and wound up buying all 4 new tires speedy service, Marco was a pleasure doing business with you. Would recommend this shop to anyone. These guys get it done and professional." },
    { "name": "Lavira Johnson", "text": "I called at the last minute to get in and have my battery replaced. I was given an exact quote, the part was in stock and I was encouraged to come in right away. When I arrived, I was greeted and checked in immediately in a very kind and professional manner by Baltazar. I was quoted 30-45 mins and it didn't feel like more than 25 and I came in about an hour before closing time. Fast and exceptional service, reasonably priced.. Will definitely patronize this business again. Pep Boys, only 5 minutes away wanted almost $300 more for the same service and wanted to keep my car overnight." },
    { "name": "Theresa Hoge", "text": "Highly recommend! Probably one of the best shops I’ve been too. Service is professional and super nice. I had to get my brakes done. They got me in the same day, were done in a few hours and explained everything to me. I also needed to get new tires and they walked me through all the options. I recently ran over a nail and they were able to patch the hole right away. Quality of work is great and the customer service is everything! Really appreciate them!" },
    { "name": "Vianey", "text": "Itsel was wonderful at explaining how snap finance worked. I was able to get what my car needed. They did a great job at replacing my compressor, and serpentine belt and last minute headlight bulb. This place is friendly and reliable highly recommend." },
    { "name": "Teryl Teeter", "text": "If you miss reliable customer service, go to Queens. They listen and stand by their work." },
    { "name": "Jeni Slagel", "text": "I had a great experience at Queens auto. They were very professional and treated me with respect no different than if I was a man. Not only did they fix my tire issue but, they looked over some work another mechanic did and confirmed it was done correctly for my piece of mind. They noticed I was missing a screw in my seat trim and just popped one in as a courtesy. I will only bring my vehicles to Queens from now on. They have a great team there. - Jeni" },
    { "name": "Sharon Balog", "text": "I have had several tires with nails in them and they have fixed them quickly and are very professional. I recently ran over a very large bolt and it wasn't ideal to fix it considering the age and wear on my tires. They showed me how to see the amount of tread left and the year of the tires. They were able to get me new tires the next day and replaced them. They are extremely reasonable and trustworthy! I wouldn't trust anyone else with fixing my truck. Everyone is great there." },
    { "name": "Rafa Marquez", "text": "Great service!! They never try to take your money \"finding\" another damages. I went to 6 places before here and all of them tried to add more service with fake damages. (As usual in almost all tune shops). They are very friendly and works fast. Definitely I'll be back!! If you go to replace a belt, they will replace your belt without excuses and fake damages to attempts to take more money from you." },
    { "name": "Donald Smith", "text": "Badly needed a couple tires. Most everybody else had a long wait. I was in and out of here in 30 minutes or so. The price was fair & the service was great." },
    { "name": "Joshua Kane", "text": "Exceptional customer service, prices, and quality of work! The boys over at queens ALWAYS take care of my vehicle repair needs in a timely fashion without being price gouged. If you are looking for an honest shop, queens is your place!" },
    { "name": "Lita", "text": "Very good work and was available when we needed help with my niece car. Reasonable price as well. Any car issues again, we will be back🥰" },
    { "name": "Mike", "text": "Saved me from having a rim fall off while driving on the highway. I had limited tools and thankfully they had me me back on my way within 10 minutes. I would have not made it to my job site on time without their help. The cost was less than a trip to McDonald's!!!" },
    { "name": "Kim Banks", "text": "Very thorough when it comes to diagnosing the service needed, they don't temporarily patch things up unlike a lot of shops in Elgin, they won't break the bank either. Lex has definitely become a trusted name in my household. My best friend recommended this shop now my husband, son and parents TRUST this shop. KUDOS Queens auto shop for winning my business because nowadays that's hard for me to TRUST anyone." },
    { "name": "Christian Abarro", "text": "Great customer service, speedy tire change, satisfied with price and outcome. Marco was a pleasure speaking with! These guys are doing gods work and will help you with your car troubles" },
    { "name": "Hannah Kellogg", "text": "I had a nail in my tire and i had originally gone to PepBoys to get it fixed but they told me i would have to leave it until noon. It was 9am. I did not have time for that. So i tried this shop. They told me it would be a 25 minute wait, but the man came out 10 minutes later. He goes out to my truck, takes my tire off, fixes the hole and puts it back on. I was on my way so fast and the price was great. I will be going back for all my other work." },
    { "name": "Rolando Gonzalez", "text": "Needed to stop by for a flat tire, fast service. Person at desk able to work on price of used tire needed. Would recommend" },
    { "name": "Antonio Saenz", "text": "brought in my truck to get the exhaust pipe repaired. they were able to finish the repair within a day at a fair price. friendly service and honest!" },
    { "name": "Terrance Boone", "text": "They were very welcoming and attentive to my needs with my vehicle. I truly appreciated that. Finding a shop that's friendly and dependable is everything. Thanks again to the guys at Queen's Auto Service" },
    { "name": "Truth", "text": "Had them fix a tire with a nail in it. They did it FAST !, and it was really reasonably priced. And the fix has held strong for better than a year now." },
    { "name": "Robert Correll", "text": "great service..took care of everything in one day..A +..been there twice more and again..great service..very prompt on getting my vehicle back to me ASAP" },
    { "name": "Zena Cortez", "text": "i went here a couple of weeks ago. great experience. i believe the front lady name is Isabel, she is very wonderful, and she was giving me great prices. i went to about 3 other shops and there prices were horrible. i’m so glad i went here thank you!" },
    { "name": "Lorin Mislevy", "text": "I took my car here about two weeks and I was so happy with the service I got. A woman named Isabel helped me out and was able to figure out right away what was wrong with my car and was able to fix it quickly and at a great price!" },
    { "name": "Polly Martinez", "text": "I went for a tune up. when I say great customer service I mean it. The front lady Isabel was so wonderful, very knowledgeable and very respectful. I have recommended about 2 of my friends to go there. Thank you so much!" },
    { "name": "Jarintzy Ramirez", "text": "The guys were very helpful and accommodating. Got me right in and quoted me a reasonable price for my brakes." },
    { "name": "i ivasyuk", "text": "Thank You for good job!!!" },
    { "name": "Edward Hall", "text": "Took my 70 maverick in there to get some new back tires.They hooked me up with a great set of skins and a great price.Alec and lex were great at taking care of me and getting my baby back on the road." },
    { "name": "서휘종", "text": "I was on my way to Chicago from Minnesota. I visited here real urgent that my engine heat rise really high. Although I visited after hours they fix the problem quick. Moreover, Mechanics are really kind and fun." },
    { "name": "Bonnie Beta", "text": "Fixed my 2008 Ford Focus ignition but had to call in a specialist to program the PCM for the ignition keys to work again. Marco was very helpful." },
    { "name": "Quintin Wells", "text": "When your vehicle is broken, call Queens Auto Services Elgin to get it fixed. A special shop with special people who work to keep your cost down and your vehicle rolling. Queens Auto Services Elgin has earned my business. Let them earn yours, too." },
    { "name": "Leonel Lomeli", "text": "Ultra clean shop and very friendly people, they gave me a really good price on a wheel alignment for my truck, I'm definitely coming back next time." },
    { "name": "Marshall Morici", "text": "Great service manager Lex, and great technicians wilmer and joel in shop. Will be bringing my service fleet from here on out. Recommend highly!" },
    { "name": "Humberto Caballero", "text": "Very respectful to clients, if you need anything come here. They do all type of service good prices as well" },
    { "name": "Anna Anderson", "text": "Marco was so kind and helped me right away during a crisis on a road trip! totally recommend!" },
    { "name": "Ed Mungai", "text": "First time I've been back since new owners took over. Service was fast and professional." },
    { "name": "Shelby Andal", "text": "Super nice. Reasonably priced. Good job!" },
    { "name": "Danny Zambrano", "text": "Good service and they will make time to fit you in." },
    { "name": "Sarah Pavao", "text": "Incredible service and really helped us out in a jam." },
    { "name": "Eduardo Vazquez", "text": "Mexican guys do amazing job!! Keep do great service." },
    { "name": "MsB Warnock", "text": "Excellent work! These guys KNOW what their doing. And they guarantee the work they do. That really says it all..." },
    { "name": "Danny Thomas", "text": "I only take my cars to queens Auto! The owner is a great reliable and very honest owner and mechanic!" },
    { "name": "cleo dillon", "text": "Extremely down to earth staff. Never felt like I was getting ripped off here." },
    { "name": "Juan Mendoza", "text": "Been coming here for years really affordable and fast service." },
    { "name": "Ana Marie De La Cruz", "text": "Great service by new owners!! They help out alot" },
    { "name": "Dangerlaw MC", "text": "Awesome service and a great team -I'll be back!!" },
    { "name": "Jose De alba", "text": "Nice people! Good attitude with the workers👍" }
];

export const faqData: FaqItem[] = [
    { qKey: 'faqQ1', aKey: 'faqA1' },
    { qKey: 'faqQ2', aKey: 'faqA2' },
    { qKey: 'faqQ3', aKey: 'faqA3' },
    { qKey: 'faqQ4', aKey: 'faqA4' },
];

export const bonusData: BonusItem[] = [
    { icon: 'tag', titleKey: 'bonus1Title', descKey: 'bonus1Desc' },
    { icon: 'search-check', titleKey: 'bonus2Title', descKey: 'bonus2Desc' },
    { icon: 'shield-check', titleKey: 'bonus3Title', descKey: 'bonus3Desc' },
    { icon: 'truck', titleKey: 'bonus4Title', descKey: 'bonus4Desc' },
    { icon: 'award', titleKey: 'bonus5Title', descKey: 'bonus5Desc' },
];