
import { Translations, Review, FaqItem, BonusItem } from './types';

export const translations: Translations = {
    en: {
        bookNowNav: "Book Now",
        heroTitle: "<span class='highlight-text'>Up to $45 Off</span> Auto Repair <span class=\"text-transparent bg-clip-text bg-gradient-to-r from-cyan-400 to-blue-500\">+ $150 in FREE Bonuses</span>",
        heroSubtitle: "Save big on your next repair and enjoy peace of mind with warranty, safety checks, and roadside protection included.",
        offer100: "When you spend $100+",
        offer200: "When you spend $200+",
        offer300: "When you spend $300+",
        heroCTA: "Claim This Offer Now -->",
        couponSent: "(Coupon code sent via text/email)",
        seeDetails: "See details",
        trustedBy: "Trusted by <span class=\"font-medium text-blue-400\">25,000+</span> Customers",
        bonusStackTitle: "What’s Included in Your Auto Repair Package",
        bonusStack1: "$15–$45 Off Repairs (tiered savings)",
        bonusStack2: "Free Multi-Point Vehicle Inspection ($79 Value)",
        bonusStack3: "Free Brake &amp; Tire Safety Check ($39 Value)",
        bonusStack4: "Roadside Assistance Included ($59 Value)",
        bonusStack5: "2-Year / 24,000-Mile Nationwide Warranty",
        bonusStackScarcity: "Only 12 repair packages left this month.",
        bonusStackDisclaimer: "*Disclaimer: Warranty and roadside assistance are provided through ProVantage Auto Repair Network. Coverage is 2 Years or 24,000 Miles (whichever comes first). Roadside services include towing, lock-out help, flat tire assistance, fluid/oil/water delivery, and battery jump start. ProVantage covers up to two claims per 12-month period for covered roadside assistance (up to $150 per claim). Restrictions may apply. <a href=\"https://provantagenetwork.com/\" target=\"_blank\" class=\"underline hover:text-cyan-400\">See full terms</a>.",
        commitmentTitle: "The Queen's Auto Commitment",
        spotsAvailable: "Spots Available",
        numbersSpeak: "The Numbers Speak of Our Commitment",
        numbersSubtitle: "“We don’t just fix cars — we’ve built trust with thousands of local drivers. Here’s why Queens Auto is Elgin’s go-to repair shop.”",
        customersServed: "Customers Served",
        averageRating: "Average Rating",
        warrantyMonth: "24-Month",
        nationwideWarranty: "Nationwide Warranty on all mechanical work",
        happyCustomers: "Happy Customers",
        averageRating2: "Average Rating",
        sameDay: "Same-Day",
        service: "Service",
        monthMileWarranty: "Month/Mile Warranty",
        formTitle: "Secure Your Spot - Get Started Here",
        formStep1: "Step 1 of 3 — Tell us what you are experiencing.",
        formStep2: "Step 2 of 3 — Your contact details.",
        formStep3: "Step 3 of 3 — Pick your preferred time.",
        symptomCheckEngine: "Check engine light is on",
        symptomNoises: "Strange noises while driving",
        symptomLeaking: "Fluid leaking under the car",
        symptomSteering: "Steering feels off or loose",
        symptomAC: "A/C not working right",
        symptomOther: "Something else is wrong (I’ll explain later)",
        nextBtn1: "Next → Lock In My Discount",
        noPaymentRequired: "No payment required — this just saves your spot.",
        firstName: "First Name",
        lastName: "Last Name",
        email: "Email",
        mobileNumber: "Mobile Number",
        vehicleDetails: "Vehicle Details",
        carYear: "Year",
        carMake: "Make",
        carModel: "Model",
        backBtn: "Back",
        nextBtn2: "Next → Pick a Time",
        availableTimes: "Available Times",
        backBtn2: "Back",
        submitBtn: "Book My Service",
        testimonialsTitle: "Trusted by Elgin Drivers",
        testimonialsSubtitle: "Elgin drivers count on Queens Auto for fast, affordable, and reliable brake service. See why 25,000+ customers won’t go anywhere else.",
        loadMore: "Load More Reviews",
        aboutUs: "About Us",
        aboutTitle: "Driven by Passion for Cars — and Care for People.",
        aboutBody: "At Queens Auto, we’re not a big chain — we’re a neighborhood shop built on trust, transparency, and true passion for what we do. Every car that comes through our doors gets treated like family, and every customer drives out knowing they got real value — not gimmicks.",
        aboutTagline: "Real people. Real service. We fix the car — and the stress.",
        address: "<svg xmlns=\"http://www.w3.org/2000/svg\" width=\"16\" height=\"16\" viewBox=\"0 0 24 24\" fill=\"none\" stroke=\"currentColor\" stroke-width=\"2\" stroke-linecap=\"round\" stroke-linejoin=\"round\" class=\"inline-block lucide lucide-map-pin mr-2 h-4 w-4 text-blue-400\"><path d=\"M20 10c0 6-8 12-8 12s-8-6-8-12a8 8 0 0 1 16 0Z\"></path><circle cx=\"12\" cy=\"10\" r=\"3\"></circle></svg>1303 Dundee Ave, 2 blocks from I-90, Elgin",
        benefitsTitle: "Peace of Mind, Guaranteed.",
        benefitsSubtitle: "We back our work with benefits that keep you covered long after you leave the shop.",
        benefit1Title: "Nationwide Warranty",
        benefit1Body: "Our 24-month/24k-mile warranty is honored at shops across the country.",
        benefit2Title: "Roadside Assistance",
        benefit2Body: "We've got your back when you're stranded. Ask about our assistance options.",
        benefit3Title: "Flexible Financing",
        benefit3Body: "Repairs shouldn't break the bank. Pay over time with our easy financing plans.",
        benefit4Title: "Family-Owned",
        benefit4Body: "We're your neighbors, not a faceless chain. Expect honest advice every time.",
        servicesEyebrow: "Comprehensive Car Care",
        servicesTitle: "Your One-Stop Shop for Auto Repair in Elgin",
        service1Title: "Routine Maintenance",
        service1Body: "Keep your vehicle running like new with our essential maintenance services, including oil changes, tire rotations, and comprehensive multi-point inspections.",
        service2Title: "Repair & Diagnostics",
        service2Body: "From a mysterious check engine light to A/C failures and complex brake issues, our expert technicians have the tools and expertise to find and fix the problem fast.",
        service3Title: "Wheels & Ride Quality",
        service3Body: "Ensure a smooth, safe ride with our complete tire services. We handle everything from new tire sales and flat repairs to precision wheel alignments and balancing.",
        teamEyebrow: "The Queens Auto Family",
        teamTitle: "Honest Mechanics, Real Service",
        teamBody: "We're not just technicians; we're car enthusiasts and your neighbors. As a family-owned shop, our reputation is built on every handshake and every repair. We treat your car like it's our own and give you the straightforward advice you deserve. No upselling, no pressure—just quality work from people who care.",
        teamBenefitTitle: "Experienced Technicians",
        teamBenefitBody: "Our team has years of hands-on experience fixing it all.",
        parallaxTitle: "Car Trouble Draining Your Wallet? Get It Fixed This Week!",
        parallaxBody: "That check engine light or strange noise wrecking your peace of mind? At Queens Auto Service, we use industry-leading tech to diagnose and fix the problem with precision. Fill out the form and get back to driving safe, and worry-free.",
        parallaxCTA: "Book Your Repair & Save →",
        serviceAreaTitle: "Proudly Serving Elgin & the Surrounding Communities",
        faqTitle: "Your Questions, Answered",
        faqSubtitle: "Honest answers to help you make the right choice for your car.",
        faq1q: "What kind of warranty do you offer on repairs?",
        faq1a: "We stand by our work with a rock-solid <strong>24-month / 24,000-mile nationwide warranty</strong> on all parts and labor. Whether you're in Elgin or on a road trip, you're covered. It's peace of mind, built-in.",
        faq2q: "Do I need an appointment, or can I just walk in?",
        faq2a: "Both! Appointments are always recommended to guarantee your spot, and you can book one easily on our site. But if you're in a pinch, just come on by. We always welcome walk-ins and will get you taken care of as quickly as possible.",
        faq3q: "How do I know I'm getting a fair price?",
        faq3a: "Transparency is key. As a family-owned shop, our reputation in Elgin means everything. We provide clear, upfront estimates before any work begins, and we'll explain exactly what your car needs and why. No jargon, no pressure, no hidden fees—ever.",
        faq4q: "What types of vehicles do you service?",
        faq4a: "We service almost all makes and models, from your daily driver sedan to SUVs and trucks. Whether it's a domestic brand like Ford or Chevy, or an import like Toyota or Honda, our experienced technicians have the tools and know-how to get the job done right.",
        faq5q: "Do you offer financing for larger repairs?",
        faq5a: "Absolutely. Unexpected car repairs shouldn't break the bank. We offer flexible financing options to help you manage the cost and get you back on the road without stress. Just ask us about our plans when you get your estimate.",
        faqStillQuestions: "Still have questions?",
        faqContactUs: "Call, during business hours to get your questions answered.",
        contactCTA: "Contact Us → (224) 635-3000",
        privacyPolicy: "Privacy Policy",
        termsOfUse: "Terms of Use",
        callUs: "Call Us:",
        modalTitle: "Offer Details",
        modalP1: "Valid only on qualifying services made in a single transaction. $15 discount requires $100–$199 in qualifying services; $30 discount requires $200–$299 in qualifying services; $45 discount requires $300 or more in qualifying services.",
        modalP2: "Limit 1 discount per customer. Excludes tires, commercial, and fleet services. Not valid in combination with any other offers, discounts, or promotions, except manufacturer rebates.",
        modalP3: "Offer valid for 30 days from the date the coupon is issued. Other terms and restrictions may apply. See Queens Auto Services for details.",
        popupTitleV2: "Wait! Don’t Miss This Auto Repair Package",
        popupSubtitleV2: "Get up to $45 Off + $150 in Free Bonuses when you book today.",
        popupBonus1: "$15–$45 Off Repairs (tiered savings)",
        popupBonus2: "Free Multi-Point Vehicle Inspection ($79 Value)",
        popupBonus3: "Free Brake & Tire Safety Check ($39 Value)",
        popupBonus4: "Roadside Assistance Included ($59 Value)",
        popupBonus5: "2-Year/24k Nationwide Warranty",
        popupCTAV2: "Claim My Repair Package →",
        popupScarcityV2: "Only 12 repair packages left this month."
    },
    es: {
        bookNowNav: "Reservar Ahora",
        heroTitle: "<span class='highlight-text'>Hasta $45 de Descuento</span> en Reparación de Autos <span class=\"text-transparent bg-clip-text bg-gradient-to-r from-cyan-400 to-blue-500\">+ $150 en Bonos GRATIS</span>",
        heroSubtitle: "Ahorra en grande en tu próxima reparación y disfruta de la tranquilidad con garantía, revisiones de seguridad y protección en carretera incluidas.",
        offer100: "Cuando gastas $100+",
        offer200: "Cuando gastas $200+",
        offer300: "Cuando gastas $300+",
        heroCTA: "Reclamar Esta Oferta Ahora -->",
        couponSent: "(Código de cupón enviado por texto/email)",
        seeDetails: "Ver detalles",
        trustedBy: "Confiado por <span class=\"font-medium text-blue-400\">25,000+</span> Clientes",
        bonusStackTitle: "Qué Incluye Tu Paquete de Reparación de Auto",
        bonusStack1: "$15–$45 de Descuento en Reparaciones (ahorros por niveles)",
        bonusStack2: "Inspección Vehicular de Múltiples Puntos Gratis (Valor de $79)",
        bonusStack3: "Revisión de Seguridad de Frenos y Llantas Gratis (Valor de $39)",
        bonusStack4: "Asistencia en Carretera Incluida (Valor de $59)",
        bonusStack5: "Garantía Nacional de 2 Años / 24,000 Millas",
        bonusStackScarcity: "Solo quedan 12 paquetes de reparación este mes.",
        bonusStackDisclaimer: "*Aviso: La garantía y la asistencia en carretera son proporcionadas a través de ProVantage Auto Repair Network. La cobertura es de 2 años o 24,000 millas (lo que ocurra primero). Los servicios de asistencia en carretera incluyen remolque, ayuda por bloqueo, asistencia por llanta ponchada, entrega de líquidos/aceite/agua y arranque de batería. ProVantage cubre hasta dos reclamos por período de 12 meses para la asistencia en carretera cubierta (hasta $150 por reclamo). Pueden aplicarse restricciones. <a href=\"https://provantagenetwork.com/\" target=\"_blank\" class=\"underline hover:text-cyan-400\">Ver términos completos</a>.",
        commitmentTitle: "El Compromiso de Queen's Auto",
        spotsAvailable: "Cupos Disponibles",
        numbersSpeak: "Los Números Hablan de Nuestro Compromiso",
        numbersSubtitle: "“No solo reparamos autos — hemos construido confianza con miles de conductores locales. Por eso Queens Auto es el taller de referencia en Elgin.”",
        customersServed: "Clientes Atendidos",
        averageRating: "Calificación Promedio",
        warrantyMonth: "Garantía de 24 Meses",
        nationwideWarranty: "Garantía a nivel nacional en todo el trabajo mecánico",
        happyCustomers: "Clientes Felices",
        averageRating2: "Calificación Promedio",
        sameDay: "Servicio el Mismo Día",
        service: "Servicio",
        monthMileWarranty: "Garantía Mes/Milla",
        formTitle: "Asegura Tu Lugar - Comienza Aquí",
        formStep1: "Paso 1 de 3 — Cuéntanos qué estás experimentando.",
        formStep2: "Paso 2 de 3 — Tus datos de contacto.",
        formStep3: "Paso 3 de 3 — Elige tu hora preferida.",
        symptomCheckEngine: "La luz de 'check engine' está encendida",
        symptomNoises: "Ruidos extraños al conducir",
        symptomLeaking: "Fuga de líquido debajo del auto",
        symptomSteering: "La dirección se siente rara o suelta",
        symptomAC: "El aire acondicionado no funciona bien",
        symptomOther: "Algo más está mal (lo explicaré después)",
        nextBtn1: "Siguiente → Asegurar Mi Descuento",
        noPaymentRequired: "No se requiere pago — esto solo guarda tu lugar.",
        firstName: "Nombre",
        lastName: "Apellido",
        email: "Correo Electrónico",
        mobileNumber: "Número de Celular",
        vehicleDetails: "Detalles del Vehículo",
        carYear: "Año",
        carMake: "Marca",
        carModel: "Modelo",
        backBtn: "Atrás",
        nextBtn2: "Siguiente → Elegir Hora",
        availableTimes: "Horas Disponibles",
        backBtn2: "Atrás",
        submitBtn: "Reservar Mi Servicio",
        testimonialsTitle: "Con la Confianza de los Conductores de Elgin",
        testimonialsSubtitle: "Los conductores de Elgin confían en Queens Auto para un servicio de frenos rápido, asequible y confiable. Ve por qué más de 25,000 clientes no van a ningún otro lado.",
        loadMore: "Cargar Más Reseñas",
        aboutUs: "Sobre Nosotros",
        aboutTitle: "Impulsados por la Pasión por los Autos — y el Cuidado por las Personas.",
        aboutBody: "En Queens Auto, no somos una gran cadena — somos un taller de barrio construido sobre la confianza, la transparencia y la verdadera pasión por lo que hacemos. Cada auto que entra por nuestras puertas es tratado como de la familia, y cada cliente se va sabiendo que obtuvo un valor real — no trucos.",
        aboutTagline: "Gente real. Servicio real. Arreglamos el auto — y el estrés.",
        address: "<svg xmlns=\"http://www.w3.org/2000/svg\" width=\"16\" height=\"16\" viewBox=\"0 0 24 24\" fill=\"none\" stroke=\"currentColor\" stroke-width=\"2\" stroke-linecap=\"round\" stroke-linejoin=\"round\" class=\"inline-block lucide lucide-map-pin mr-2 h-4 w-4 text-blue-400\"><path d=\"M20 10c0 6-8 12-8 12s-8-6-8-12a8 8 0 0 1 16 0Z\"></path><circle cx=\"12\" cy=\"10\" r=\"3\"></circle></svg>1303 Dundee Ave, a 2 cuadras de la I-90, Elgin",
        benefitsTitle: "Tranquilidad, Garantizada.",
        benefitsSubtitle: "Respaldamos nuestro trabajo con beneficios que te mantienen cubierto mucho después de que dejas el taller.",
        benefit1Title: "Garantía Nacional",
        benefit1Body: "Nuestra garantía de 24 meses/24k millas es válida en talleres de todo el país.",
        benefit2Title: "Asistencia en Carretera",
        benefit2Body: "Te cubrimos cuando te quedas varado. Pregunta por nuestras opciones de asistencia.",
        benefit3Title: "Financiamiento Flexible",
        benefit3Body: "Las reparaciones no deberían arruinarte. Paga a lo largo del tiempo con nuestros sencillos planes de financiamiento.",
        benefit4Title: "De Propiedad Familiar",
        benefit4Body: "Somos tus vecinos, no una cadena sin rostro. Espera consejos honestos siempre.",
        servicesEyebrow: "Cuidado Integral del Automóvil",
        servicesTitle: "Tu Taller Integral de Reparación de Autos en Elgin",
        service1Title: "Mantenimiento de Rutina",
        service1Body: "Mantén tu vehículo como nuevo con nuestros servicios de mantenimiento esenciales, incluyendo cambios de aceite, rotación de llantas e inspecciones completas de múltiples puntos.",
        service2Title: "Reparación y Diagnóstico",
        service2Body: "Desde una misteriosa luz de 'check engine' hasta fallas del A/C y problemas complejos de frenos, nuestros técnicos expertos tienen las herramientas y la experiencia para encontrar y solucionar el problema rápidamente.",
        service3Title: "Ruedas y Calidad de Marcha",
        service3Body: "Asegura una conducción suave y segura con nuestros servicios completos de llantas. Manejamos todo, desde la venta de llantas nuevas y reparaciones de pinchazos hasta alineaciones y balanceo de ruedas de precisión.",
        teamEyebrow: "La Familia de Queens Auto",
        teamTitle: "Mecánicos Honestos, Servicio Real",
        teamBody: "No somos solo técnicos; somos entusiastas de los autos y tus vecinos. Como taller familiar, nuestra reputación se construye con cada apretón de manos y cada reparación. Tratamos tu auto como si fuera nuestro y te damos el consejo directo que mereces. No upselling, sin presión—solo trabajo de calidad de personas que se preocupan.",
        teamBenefitTitle: "Técnicos Experimentados",
        teamBenefitBody: "Nuestro equipo tiene años de experiencia práctica arreglando de todo.",
        parallaxTitle: "¿Problemas con el Auto Drenando tu Billetera? ¡Repáralo Esta Semana!",
        parallaxBody: "¿Esa luz de 'check engine' o ese ruido extraño que te quita la tranquilidad? En Queens Auto Service, usamos tecnología líder en la industria para diagnosticar y solucionar el problema con precisión. Llena el formulario y vuelve a conducir seguro y sin preocupaciones.",
        parallaxCTA: "Reserva Tu Reparación y Ahorra →",
        serviceAreaTitle: "Sirviendo con Orgullo a Elgin y las Comunidades Circundantes",
        faqTitle: "Tus Preguntas, Respondidas",
        faqSubtitle: "Respuestas honestas para ayudarte a tomar la decisión correcta para tu auto.",
        faq1q: "¿Qué tipo de garantía ofrecen en las reparaciones?",
        faq1a: "Respaldamos nuestro trabajo con una sólida <strong>garantía nacional de 24 meses / 24,000 millas</strong> en todas las piezas y mano de obra. Ya sea que estés en Elgin o en un viaje por carretera, estás cubierto. Es tranquilidad incorporada.",
        faq2q: "¿Necesito una cita o puedo simplemente llegar?",
        faq2a: "¡Ambas! Siempre se recomiendan las citas para garantizar tu lugar, y puedes reservar una fácilmente en nuestro sitio. Pero si estás en un apuro, simplemente ven. Siempre damos la bienvenida a quienes llegan sin cita y te atenderemos lo más rápido posible.",
        faq3q: "¿Cómo sé que estoy obteniendo un precio justo?",
        faq3a: "La transparencia es clave. Como un taller familiar, nuestra reputación en Elgin lo es todo. Proporcionamos presupuestos claros y por adelantado antes de que comience cualquier trabajo, y te explicaremos exactamente qué necesita tu auto y por qué. Sin jerga, sin presión, sin cargos ocultos, nunca.",
        faq4q: "¿Qué tipos de vehículos atienden?",
        faq4a: "Atendemos casi todas las marcas y modelos, desde tu sedán de uso diario hasta SUVs y camionetas. Ya sea una marca nacional como Ford o Chevy, o una de importación como Toyota u Honda, nuestros técnicos experimentados tienen las herramientas y el conocimiento para hacer el trabajo bien.",
        faq5q: "¿Ofrecen financiamiento para reparaciones más grandes?",
        faq5a: "Absolutamente. Las reparaciones de auto inesperadas no deberían arruinarte. Ofrecemos opciones de financiamiento flexible para ayudarte a manejar el costo y volver a la carretera sin estrés. Solo pregúntanos sobre nuestros planes cuando obtengas tu presupuesto.",
        faqStillQuestions: "¿Aún tienes preguntas?",
        faqContactUs: "Llama durante el horario de atención para que te respondan tus preguntas.",
        contactCTA: "Contáctanos → (224) 635-3000",
        privacyPolicy: "Política de Privacidad",
        termsOfUse: "Términos de Uso",
        callUs: "Llámanos:",
        modalTitle: "Detalles de la Oferta",
        modalP1: "Válido solo en servicios calificados realizados en una sola transacción. El descuento de $15 requiere de $100 a $199 en servicios calificados; el descuento de $30 requiere de $200 a $299 en servicios calificados; el descuento de $45 requiere $300 o más en servicios calificados.",
        modalP2: "Límite de 1 descuento por cliente. Excluye llantas, servicios comerciales y de flota. No es válido en combinación con ninguna otra oferta, descuento o promoción, excepto los reembolsos del fabricante.",
        modalP3: "La oferta es válida por 30 días a partir de la fecha de emisión del cupón. Pueden aplicarse otros términos y restricciones. Consulte a Queens Auto Services para obtener más detalles.",
        popupTitleV2: "¡Espera! No te pierdas este paquete de reparación de autos",
        popupSubtitleV2: "Obtén hasta $45 de descuento + $150 en bonos gratis al reservar hoy.",
        popupBonus1: "$15–$45 de descuento en reparaciones (ahorros por niveles)",
        popupBonus2: "Inspección vehicular de múltiples puntos gratuita (valor de $79)",
        popupBonus3: "Revisión de seguridad de frenos y llantas gratuita (valor de $39)",
        popupBonus4: "Asistencia en carretera incluida (valor de $59)",
        popupBonus5: "Garantía nacional de 2 años/24k millas",
        popupCTAV2: "Reclamar mi paquete de reparación →",
        popupScarcityV2: "Solo quedan 12 paquetes de reparación este mes."
    }
};

export const testimonials: Review[] = [
    { name: "Mark Devino", text: "I got fast, friendly service here for a flat repair. Without any kind of appointment I got the tire fixed while I waited maybe 25 minutes. The repair was inexpensive. Great shop I will definitely be back." },
    { name: "Bashar Danial", text: "Gino and the Team, Wow!!! I recently had the misfortune of breaking down on the side of the road with a bad tire, called Queens Auto Service and spoke with Gino. They were very receptive and responsive, we got the vehicle to their shop, they immediately jumped into action and replaced the bad tire with a new tire and had us back on the road, all of this in under one hour!!! I highly recommend Queens Auto Service and Gino and the Team at this shop, top-notch!! Thank you for the help and great service." },
    { name: "A C", text: "HIGHLY RECOMMEND QUEENS TIRE IN ELGIN. Friendliness customer service. Prices are affordable, no extra unnecessary add ons. This will be my ONLY go to place. Much more than just tires" },
    { name: "Nursultan Abeuov", text: "Good place to get your tire, balancing, Alignment and more. Always good quality. Ill do all my pickup trucks alignment here, never regret it. Nick Abeuov🇰🇿" },
    { name: "Kristin Kastern", text: "Tires and axle shaft. They were amazing. I am new to the area and I am very happy 😊 with my service. They were honest and were able to fit me in on holiday weekend. The pricing was great. They even gave me really good advice about the car and tires. I am going to them in the future with all my cars. Thank you so much." },
    { name: "Tim Chapman", text: "Great customer service, went in for a second opinion for tire patch, nail in tire and advised not repairable too close to outer wall of tire. Good price and wound up buying all 4 new tires speedy service, Marco was a pleasure doing business with you. Would recommend this shop to anyone. These guys get it done and professional." },
    { name: "Lavira Johnson", text: "I called at the last minute to get in and have my battery replaced. I was given an exact quote, the part was in stock and I was encouraged to come in right away. When I arrived, I was greeted and checked in immediately in a very kind and professional manner by Baltazar. I was quoted 30-45 mins and it didn't feel like more than 25 and I came in about an hour before closing time. Fast and exceptional service, reasonably priced.. Will definitely patronize this business again. Pep Boys, only 5 minutes away wanted almost $300 more for the same service and wanted to keep my car overnight." },
    { name: "Theresa Hoge", text: "Highly recommend! Probably one of the best shops I’ve been too. Service is professional and super nice. I had to get my brakes done. They got me in the same day, were done in a few hours and explained everything to me. I also needed to get new tires and they walked me through all the options. I recently ran over a nail and they were able to patch the hole right away. Quality of work is great and the customer service is everything! Really appreciate them!" },
    { name: "Vianey", text: "Itsel was wonderful at explaining how snap finance worked. I was able to get what my car needed. They did a great job at replacing my compressor, and serpentine belt and last minute headlight bulb. This place is friendly and reliable highly recommend." },
    { name: "Teryl Teeter", text: "If you miss reliable customer service, go to Queens. They listen and stand by their work." },
];

export const faqData: FaqItem[] = [
    { qKey: 'faq1q', aKey: 'faq1a' },
    { qKey: 'faq2q', aKey: 'faq2a' },
    { qKey: 'faq3q', aKey: 'faq3a' },
    { qKey: 'faq4q', aKey: 'faq4a' },
    { qKey: 'faq5q', aKey: 'faq5a' },
];

export const commitmentSlides: string[] = [
    'https://queensautoserviceselgin.com/wp-content/uploads/2025/09/Queens-Auto-Auto-Repair-001.webp',
    'https://queensautoserviceselgin.com/wp-content/uploads/2025/09/Queens-Auto-Auto-Repair-002.webp',
    'https://queensautoserviceselgin.com/wp-content/uploads/2025/09/Queens-Auto-Auto-Repair-003.webp',
    'https://queensautoserviceselgin.com/wp-content/uploads/2025/09/Queens-Auto-Auto-Repair-004.webp',
    'https://queensautoserviceselgin.com/wp-content/uploads/2025/09/Queens-Auto-Auto-Repair-005.webp'
];

export const bonusStackData: string[] = [
    'bonusStack1',
    'bonusStack2',
    'bonusStack3',
    'bonusStack4',
    'bonusStack5',
];

export const whyChooseUsData = [
    { valueKey: 'happyCustomers', labelKey: 'happyCustomers' },
    { valueKey: 'averageRating2', labelKey: 'averageRating2' },
    { valueKey: 'sameDay', labelKey: 'service' },
    { valueKey: 'monthMileWarranty', labelKey: 'monthMileWarranty' }
];

export const benefitsData = [
    { icon: 'shield-check', titleKey: 'benefit1Title', bodyKey: 'benefit1Body' },
    { icon: 'truck', titleKey: 'benefit2Title', bodyKey: 'benefit2Body' },
    { icon: 'credit-card', titleKey: 'benefit3Title', bodyKey: 'benefit3Body' },
    { icon: 'home', titleKey: 'benefit4Title', bodyKey: 'benefit4Body' },
];

export const serviceData = [
    { titleKey: 'service1Title', bodyKey: 'service1Body', imgSrc: 'https://queensautoserviceselgin.com/wp-content/uploads/2025/09/Queens-Auto-Services-Elgin-AC-Repair-001.webp' },
    { titleKey: 'service2Title', bodyKey: 'service2Body', imgSrc: 'https://queensautoserviceselgin.com/wp-content/uploads/2025/09/Queens-Auto-Services-Elgin-Auto-Repair-001-scaled.webp' },
    { titleKey: 'service3Title', bodyKey: 'service3Body', imgSrc: 'https://queensautoserviceselgin.com/wp-content/uploads/2025/09/Queens-Auto-Services-ELgin-New-Tires-001.webp' },
];

export const serviceAreaData = [
    "Elgin", "Gilberts", "South Elgin", "Sleepy Hollow", "West Dundee", "Streamwood", "East Dundee", "Bartlett"
];
